from tkinter import *
from tube_dl import Youtube
root=Tk()
us=StringVar()
ps=StringVar()
lnk=StringVar()
root.title("Param's 720p YTD")
root.geometry("350x300")
lb0=Label(root,text="\t \t ")
lb0.pack()
lb1=Label(root,text="Username")
lb1.pack()
en1=Entry(root,width=20)
en1.pack()
lb2=Label(root,text="Password:")
lb2.pack()
en2=Entry(root,width=20,show='*')
en2.pack()

def openNewWin():
    print("NewWin")
    us=en1.get()
    ps=en2.get()
    if(us=='a' and ps=='b'):
        NewWin=Toplevel(root)
        NewWin.geometry("350x300")
        lb0=Label(NewWin,text="\t \t ")
        lb0.pack()
        lbA1=Label(NewWin,text="Enter Link here")
        lbA1.pack()
        enA1=Entry(NewWin,width="50")
        enA1.pack()
        def getLink():
            lnk=enA1.get()
            print(lnk)
            # yt=Youtube(lnk)
            Youtube(lnk).formats.filter_by(quality='720p')[0].download(path='F:/')
        lb3=Label(NewWin,text="\t \t ")
        lb3.pack()
        btA1=Button(NewWin,text="Download",command=getLink)
        btA1.pack()
        lb5=Label(NewWin,text="\t \t ")
        lb5.pack()
        lb4=Label(NewWin,text="File will be Saved at F:/")
        lb4.pack()
btn1=Button(root,text="Login",command=openNewWin)
lb3=Label(root,text="\t \t ")
lb3.pack()
btn1.pack()
root.mainloop()
